
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-postgres-secret"
type: Opaque
stringData:
  postgres-username: {{ .Values.postgresql.auth.username | quote }}
  postgres-password: {{ .Values.postgresql.auth.password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-redis-secret"
type: Opaque
stringData:
  redis-password: {{ .Values.redis.auth.password | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-backend-secret"
type: Opaque
stringData:
  jwt-secret: {{ .Values.backend.env.jwtSecret | quote }}
  root-password: {{ .Values.backend.env.appRootPassword | quote }}