apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.backend.name }}-service"
  labels:
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.backend.probes.managementPort }}"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
  - name: management
    protocol: TCP
    port: {{ .Values.backend.probes.managementPort }}
    targetPort: {{ .Values.backend.probes.managementPort }}