apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-backend-config"
  labels:
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.config.springProfile | quote }}
  SPRING_DATA_REDIS_HOST: {{ printf "%s-redis-ha-headless" .Release.Name | quote }} 
  SPRING_DATA_REDIS_PORT: {{ .Values.config.redisPort | quote }}
  CORS_ALLOWED_ORIGINS: {{ printf "http://%s,https://%s" .Values.ingress.host .Values.ingress.host | quote }}
  SERVER_SERVLET_CONTEXT_PATH: {{ .Values.config.contextPath | quote }}
  MANAGEMENT_SERVER_PORT: {{ .Values.config.managementPort | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: {{ .Values.config.probesEnabled | quote }}
  ROOT_USERNAME: {{ .Values.config.rootUsername | quote }}