{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: {{ .Values.ingress.paths.backend }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Values.backend.name }}-service
            port:
              number: {{ .Values.backend.service.port }}
      - path: {{ .Values.ingress.paths.frontend }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Values.frontend.name }}-service
            port:
              number: {{ .Values.frontend.service.port }}
{{- end }}