{{- if .Values.postgresHa.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-postgres-ha-secret"
  labels:
    app.kubernetes.io/name: {{ .Values.postgresHa.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  # Corrected keys to align with official PostgreSQL image variables
  POSTGRES_USER: {{ .Values.postgresHa.secret.dbUsername | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresHa.secret.dbPassword | quote }}
  POSTGRES_REPLICATION_PASSWORD: {{ .Values.postgresHa.secret.replicationPassword | quote }}
{{- end }}