apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
  labels:
    app.kubernetes.io/name: {{ .Values.backend.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: {{ printf "jdbc:postgresql://%s-postgres-ha-service:5432/%s" .Release.Name .Values.postgresHa.dbName | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresHa.secret.dbUsername | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresHa.secret.dbPassword | quote }}
  JWT_SECRET: {{ .Values.config.jwtSecret | quote }}
  ROOT_PASSWORD: {{ .Values.config.rootPassword | quote }}