apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.fullname" . }}-grafana-admin
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ .Values.grafana.admin.user | b64enc }}
  admin-password: {{ .Values.grafana.admin.password | b64enc }}
