apiVersion: v1
kind: Service
metadata:
  name: {{ include "monitoring.fullname" . }}-kube-state-metrics
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: {{ .Values.kubeStateMetrics.service.type }}
  ports:
    - port: {{ .Values.kubeStateMetrics.service.port }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    - port: {{ .Values.kubeStateMetrics.service.telemetryPort }}
      targetPort: telemetry
      protocol: TCP
      name: telemetry
  selector:
    {{- include "kube-state-metrics.selectorLabels" . | nindent 4 }}
