apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "monitoring.fullname" . }}-kube-state-metrics
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "monitoring.fullname" . }}-kube-state-metrics
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - endpoints
  verbs: ["list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - daemonsets
  - deployments
  - replicasets
  verbs: ["list", "watch"]
- apiGroups: ["batch"]
  resources:
  - cronjobs
  - jobs
  verbs: ["list", "watch"]
- apiGroups: ["autoscaling"]
  resources:
  - horizontalpodautoscalers
  verbs: ["list", "watch"]
- apiGroups: ["policy"]
  resources:
  - poddisruptionbudgets
  verbs: ["list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
  - networkpolicies
  - ingresses
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "monitoring.fullname" . }}-kube-state-metrics
  labels:
    {{- include "kube-state-metrics.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "monitoring.fullname" . }}-kube-state-metrics
subjects:
- kind: ServiceAccount
  name: {{ include "monitoring.fullname" . }}-kube-state-metrics
  namespace: {{ .Release.Namespace }}
