apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "monitoring.fullname" . }}-prometheus-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      # - "first_rules.yml"
      # - "second_rules.yml"
    
    scrape_configs:
      # Scrape Prometheus itself
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      # Spring Boot Backend Metrics (Actuator)
      - job_name: 'rateflix-backend'
        static_configs:
          - targets: ['{{ .Values.rateflixReleaseName }}-backend-service:8081']
        metrics_path: '/actuator/prometheus'
        scrape_interval: 30s
      
      # PostgreSQL Exporter Metrics
      - job_name: 'postgres-exporter'
        static_configs:
          - targets: ['{{ .Values.rateflixReleaseName }}-postgres-ha-service:9187']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      # Redis Exporter Metrics
      - job_name: 'redis-exporter'
        static_configs:
          - targets: ['{{ .Values.rateflixReleaseName }}-redis-ha-service:9121']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      # Frontend Nginx Exporter Metrics
      - job_name: 'frontend-nginx'
        static_configs:
          - targets: ['{{ .Values.rateflixReleaseName }}-frontend-service:9113']
        metrics_path: '/metrics'
        scrape_interval: 30s
      
      # Kubernetes Metrics from kube-state-metrics
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['{{ include "monitoring.fullname" . }}-kube-state-metrics:8080']
        metrics_path: '/metrics'
        scrape_interval: 30s
